services:
  # Project services
  api-service:
    working_dir: /app
    build:
      context: .
      dockerfile: deploy/api/Dockerfile
    container_name: api_service
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb-service
    ports:
      - 80:80

  # bot-service:
  #   working_dir: /app
  #   build:
  #     context: .
  #     dockerfile: deploy/bot/Dockerfile
  #   container_name: bot_service
  #   restart: always
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres-service

  # Mongo-db
  mongodb-service:
    image: mongo:latest
    container_name: db_service
    restart: always
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    ports:
      - 27017:27017

  # Postgresql
  # postgres-service:
  #   image: postgres
  #   container_name: postgres-db
  #   restart: always
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   env_file:
  #     - .env
  #   ports:
  #     - 54032:5432

  redis:
    image: redis
    container_name: redis_server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - 55040:5540
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis

volumes:
  mongo_data:
  redis_data:
  redisinsight_data:
  # pgdata:
